sonar.projectKey=bookmanager
sonar.organization=zeineb08

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=BookManager
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=frontend/src,backend/src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude test and coverage files from being analyzed
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
