#!/usr/bin/env bash
# ============================================================
# BookManager – VM Bootstrap Script (cloud-init compatible)
# ============================================================
# Runs as root on each new VM in the Scale Set.
# This is the same logic as the Terraform cloud-init,
# provided here as a standalone script for debugging
# and manual re-runs.
#
# Usage (after SSH via Bastion):
#   sudo bash /opt/bookmanager/scripts/vm-init.sh
# ============================================================
set -euo pipefail

LOG_FILE="/var/log/bookmanager-init.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "============================================================"
echo " BookManager VM Bootstrap – $(date)"
echo "============================================================"

APP_DIR="/opt/bookmanager"
ADMIN_USER="bookmanager"

# ─── 1. System Update ────────────────────────────────────────
echo "[1/7] Updating system packages..."
apt-get update -q
apt-get upgrade -y -q
apt-get install -y curl jq git unzip apt-transport-https ca-certificates gnupg lsb-release

# ─── 2. Install Docker ───────────────────────────────────────
echo "[2/7] Installing Docker CE..."
if ! command -v docker &>/dev/null; then
  # Add Docker's official GPG key
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  # Add Docker repository
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update -q
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
fi

systemctl enable docker
systemctl start docker
usermod -aG docker "$ADMIN_USER" 2>/dev/null || true
echo "Docker version: $(docker --version)"

# ─── 3. Install Azure CLI ────────────────────────────────────
echo "[3/7] Installing Azure CLI..."
if ! command -v az &>/dev/null; then
  curl -sL https://aka.ms/InstallAzureCLIDeb | bash
fi
echo "Azure CLI version: $(az --version | head -1)"

# ─── 4. Fetch Secrets from Key Vault (Managed Identity) ──────
echo "[4/7] Fetching secrets from Azure Key Vault..."

# Request access token from the Instance Metadata Service (IMDS)
# This is the VM's Managed Identity token — no password needed
IMDS_URL="http://169.254.169.254/metadata/identity/oauth2/token"
TOKEN=$(curl -s -H "Metadata: true" \
  "${IMDS_URL}?api-version=2018-02-01&resource=https://vault.azure.net" \
  | jq -r '.access_token')

if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
  echo "ERROR: Could not get Managed Identity token. Is the identity attached to this VM?"
  exit 1
fi

# Determine Key Vault name from instance metadata tags or environment
VAULT_NAME="${KEYVAULT_NAME:-bookmanager-kv}"
VAULT_URL="https://${VAULT_NAME}.vault.azure.net"

echo "Reading secrets from: $VAULT_URL"

fetch_secret() {
  local secret_name="$1"
  curl -sf -H "Authorization: Bearer $TOKEN" \
    "${VAULT_URL}/secrets/${secret_name}?api-version=7.3" \
    | jq -r '.value'
}

MONGODB_URI=$(fetch_secret "mongodb-uri")
JWT_SECRET=$(fetch_secret "jwt-secret")

echo "Secrets fetched successfully."

# ─── 5. Create Application Environment File ──────────────────
echo "[5/7] Creating application environment file..."
mkdir -p "$APP_DIR"

cat > "$APP_DIR/.env" <<EOF
# Generated by vm-init.sh on $(date)
# DO NOT EDIT MANUALLY — re-run vm-init.sh to regenerate

PORT=3000
MONGODB_URI=${MONGODB_URI}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=7d
CORS_ORIGIN=*
VITE_API_URL=/api
NODE_ENV=production
EOF

chmod 600 "$APP_DIR/.env"
echo ".env file created."

# ─── 6. Login to ACR and Start Containers ────────────────────
echo "[6/7] Logging into ACR and starting containers..."

ACR_NAME="${ACR_NAME:-bookmanageracr}"

# Use Managed Identity to authenticate to ACR (no docker login with password)
az login --identity --output none
az acr login --name "$ACR_NAME"

# Pull latest images
cd "$APP_DIR"
docker compose pull

# Start all services
docker compose up -d --force-recreate --remove-orphans

echo "Containers started:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

# ─── 7. Health Check ─────────────────────────────────────────
echo "[7/7] Running health check..."
sleep 15  # Give containers time to initialize

MAX_RETRIES=10
RETRY_COUNT=0
while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
  if curl -sf "http://localhost:3000/api/health" &>/dev/null; then
    echo "✅ Backend health check PASSED"
    break
  fi
  RETRY_COUNT=$((RETRY_COUNT + 1))
  echo "Health check attempt $RETRY_COUNT/$MAX_RETRIES... waiting 10s"
  sleep 10
done

if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
  echo "⚠️  Health check failed after $MAX_RETRIES attempts"
  echo "Check: docker logs bookmanager-backend"
fi

echo ""
echo "============================================================"
echo " Bootstrap complete! $(date)"
echo " App URL: http://\$(curl -s ifconfig.me)"
echo " Logs:    $LOG_FILE"
echo "============================================================"
